# Generated by Django 4.1.1 on 2022-12-21 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeSuper',
            fields=[
                ('Co_id', models.AutoField(primary_key=True, serialize=False)),
                ('CO_name', models.CharField(max_length=50)),
                ('CO_addrss', models.CharField(max_length=50)),
                ('CO_email', models.CharField(max_length=50)),
                ('CO_pno', models.CharField(max_length=10)),
                ('CO_prn', models.CharField(max_length=15)),
                ('CO_gender', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='company',
            fields=[
                ('C_id', models.AutoField(primary_key=True, serialize=False)),
                ('C_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='compper',
            fields=[
                ('P_id', models.AutoField(primary_key=True, serialize=False)),
                ('P_fname', models.CharField(max_length=50)),
                ('P_lname', models.CharField(max_length=50)),
                ('P_email', models.CharField(max_length=70)),
                ('P_pnol', models.CharField(max_length=11)),
                ('P_gender', models.CharField(max_length=1)),
                ('PC', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='management.company')),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Loginid', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('S_id', models.AutoField(primary_key=True, serialize=False)),
                ('S_fname', models.CharField(max_length=30)),
                ('S_mname', models.CharField(max_length=30)),
                ('S_lname', models.CharField(max_length=30)),
                ('S_email', models.CharField(max_length=30)),
                ('S_address', models.CharField(max_length=50)),
                ('S_prn', models.CharField(max_length=15)),
                ('S_geneder', models.CharField(max_length=1)),
                ('S_contact', models.CharField(max_length=10)),
                ('S_m', models.BooleanField(default=False)),
                ('S_e', models.BooleanField(default=False)),
                ('S_cm', models.BooleanField(default=False)),
                ('S_ce', models.BooleanField(default=False)),
                ('CE_C', models.BooleanField(default=False)),
                ('CE_S', models.BooleanField(default=False)),
                ('PE_S', models.BooleanField(default=False)),
                ('PE_C', models.BooleanField(default=False)),
                ('SC', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='management.company')),
                ('SCO', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='management.collegesuper')),
                ('comper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='management.compper')),
            ],
        ),
        migrations.CreateModel(
            name='progresseval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Taskperfo', models.IntegerField()),
                ('workcomplete', models.IntegerField()),
                ('Weekreport', models.IntegerField()),
                ('repowrit', models.IntegerField()),
                ('PE_total', models.IntegerField()),
                ('PEF', models.IntegerField()),
                ('PE', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='management.student')),
            ],
            options={
                'unique_together': {('PE', 'PEF')},
            },
        ),
        migrations.CreateModel(
            name='mideterm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domainandtech', models.IntegerField()),
                ('presentation', models.IntegerField()),
                ('communication', models.IntegerField()),
                ('questionans', models.IntegerField()),
                ('total', models.IntegerField()),
                ('SF', models.IntegerField()),
                ('SM', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='management.student')),
            ],
            options={
                'unique_together': {('SM', 'SF')},
            },
        ),
        migrations.CreateModel(
            name='Endterm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('implemen', models.IntegerField()),
                ('observa', models.IntegerField()),
                ('present', models.IntegerField()),
                ('communic', models.IntegerField()),
                ('qanda', models.IntegerField()),
                ('E_total', models.IntegerField()),
                ('SEF', models.IntegerField()),
                ('SE', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='management.student')),
            ],
            options={
                'unique_together': {('SE', 'SEF')},
            },
        ),
        migrations.CreateModel(
            name='comeval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.IntegerField()),
                ('collect', models.IntegerField()),
                ('Team', models.IntegerField()),
                ('oralwrit', models.IntegerField()),
                ('punctuality', models.IntegerField()),
                ('CE_total', models.IntegerField()),
                ('CEF', models.IntegerField()),
                ('CE', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='management.student')),
            ],
            options={
                'unique_together': {('CE', 'CEF')},
            },
        ),
    ]
