# Generated by Django 4.1.1 on 2022-10-01 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeSuper',
            fields=[
                ('Co_id', models.IntegerField(primary_key=True, serialize=False)),
                ('CO_name', models.CharField(max_length=50)),
                ('CO_addrss', models.CharField(max_length=50)),
                ('CO_email', models.CharField(max_length=50)),
                ('CO_pno', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('S_id', models.AutoField(primary_key=True, serialize=False)),
                ('S_fname', models.CharField(max_length=30)),
                ('S_mname', models.CharField(max_length=30)),
                ('S_lname', models.CharField(max_length=30)),
                ('S_email', models.CharField(max_length=30)),
                ('SCO', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='management.collegesuper')),
            ],
        ),
    ]
