# Generated by Django 4.1.1 on 2022-12-17 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_student_comper'),
    ]

    operations = [
        migrations.AddField(
            model_name='comeval',
            name='CE_C',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comeval',
            name='CE_S',
            field=models.BooleanField(default=False),
        ),
    ]
