# Generated by Django 4.1.1 on 2022-10-01 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_collegesuper_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegesuper',
            name='CO_pno',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='collegesuper',
            name='Co_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
