# Generated by Django 4.1.1 on 2022-10-01 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_alter_collegesuper_co_pno_alter_collegesuper_co_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='mideterm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domainandtech', models.IntegerField()),
                ('profesethi', models.IntegerField()),
                ('interpersonatl', models.IntegerField()),
                ('presentation', models.IntegerField()),
                ('communication', models.IntegerField()),
                ('taskcompleted', models.IntegerField()),
                ('questionans', models.IntegerField()),
                ('total', models.IntegerField()),
                ('SM', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='management.student')),
            ],
        ),
    ]
