# Generated by Django 4.1.1 on 2022-12-17 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_comeval_ce_c_comeval_ce_s'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comeval',
            name='CE_C',
        ),
        migrations.RemoveField(
            model_name='comeval',
            name='CE_S',
        ),
        migrations.AddField(
            model_name='student',
            name='CE_C',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='CE_S',
            field=models.BooleanField(default=False),
        ),
    ]
