# Generated by Django 4.1.1 on 2022-10-01 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_mideterm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endterm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background', models.IntegerField()),
                ('scopeandobj', models.IntegerField()),
                ('implemen', models.IntegerField()),
                ('observa', models.IntegerField()),
                ('domain', models.IntegerField()),
                ('presentation', models.IntegerField()),
                ('communic', models.IntegerField()),
                ('interper', models.IntegerField()),
                ('profess', models.IntegerField()),
                ('qanda', models.IntegerField()),
                ('E_total', models.IntegerField()),
                ('SE', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='management.student')),
            ],
        ),
    ]
