# Generated by Django 4.1.1 on 2022-10-09 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_endterm'),
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('C_id', models.AutoField(primary_key=True, serialize=False)),
                ('C_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='collegesuper',
            name='CO_prn',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='S_address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='S_contact',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='S_geneder',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='S_prn',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
