# Generated by Django 4.1.1 on 2022-10-09 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_rename_presentation_endterm_present_student_sc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='SCO',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='management.collegesuper'),
        ),
    ]
