# Generated by Django 4.1.1 on 2022-10-09 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_alter_student_sco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='SCO',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='management.collegesuper'),
        ),
    ]
