# Generated by Django 4.1.1 on 2022-11-03 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_alter_student_sco'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cendterm',
            name='id',
        ),
        migrations.RemoveField(
            model_name='cmideterm',
            name='id',
        ),
        migrations.RemoveField(
            model_name='endterm',
            name='id',
        ),
        migrations.RemoveField(
            model_name='mideterm',
            name='id',
        ),
        migrations.AddField(
            model_name='company',
            name='C_email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cendterm',
            name='C_SE',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='management.student'),
        ),
        migrations.AlterField(
            model_name='cmideterm',
            name='C_SM',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='management.student'),
        ),
        migrations.AlterField(
            model_name='endterm',
            name='SE',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='management.student'),
        ),
        migrations.AlterField(
            model_name='mideterm',
            name='SM',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='management.student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='S_address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='S_contact',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='S_geneder',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='S_prn',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
