# Generated by Django 4.1.1 on 2022-11-04 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_remove_cendterm_id_remove_cmideterm_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='S_address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='S_contact',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='S_geneder',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='student',
            name='S_prn',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
